volumes:
  pg_data:
  static:
  media:
  

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  frontend:
    build: ./frontend
    image: foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  backend:
    build: 
      context: ./backend
      args: 
        - ENV=${ENV}
    image: foodgram_backend
    env_file: .env
    depends_on:
      - db
      - frontend
    volumes:
      - static:/backend_static
      - media:/media
  gateway:
    build: ./gateway
    image: foodgram_gateway
    ports:
      - 9000:80
    depends_on:
      - backend
    volumes:
      - static:/staticfiles
      - media:/media