[tool.black]
line-length = 79
skip-string-normalization = true
exclude = '''
/(
    tests|
    migrations|
    static|
    venv|
    .venv|
    .git|
)/
'''

[tool.isort]
profile = "black"  
known_third_party = ["django", "requests"]  
known_first_party = ["api", "recipes", "users", "core", "foodgram_backend"] 
line_length = 79 
multi_line_output = 3
combine_as_imports = true 
order_by_type = true
skip = ["migrations", "static", "venv", ".venv", ".git", "tests"]