"""Контстанты для приложения recipes."""

RECIPE_NAME_MAX_LENGTH: int = 256
RECIPE_NAME_PREVIEW_MAX_LENGTH: int = 50
COOKING_TIME_MIN: int = 1
INGREDIENT_NAME_MAX_LENGTH: int = 128
INGREDIENT_NAME_PREVIEW_MAX_LENGTH: int = 50
MEASUREMENT_UNIT_MAX_LENGTH: int = 64
TAG_NAME_MAX_LENGTH: int = 32
TAG_SLUG_MAX_LENGTH: int = 32
